graph: Graph.cpp Depth-First-Search.cpp Breath-first-search.cpp shortest-path.cpp  main.cpp
	clang++ Graph.cpp Depth-First-Search.cpp Breath-first-search.cpp shortest-path.cpp  main.cpp  -o graph -std=c++11

clean:
	rm graph
